export const DefinedCategories: Record<string, string[]> = {
	Educación: [
		"Matemáticas",
		"Inglés",
		"Química",
		"Economía",
		"Filosofía",
		"Psicología",
		"Geografía",
	],
	Belleza: ["Maquillaje", "Peluquería", "Estilista", "Manicurista"],
	Turismo: ["Guía", "Traductor", "Transportador", "Hospedador"],
	Seguridad: ["Escolta", "Vigilancia", "Acompañamiento", "Detective"],
	Construcción: [
		"Arquitecto",
		"Ingeniero civil",
		"Oficial",
		"Obrero",
		"Mecánico",
	],
	Mantenimiento: [
		"Aseo",
		"Electrodomésticos",
		"Servicios generales",
		"Cámaras de Videovigilancia",
	],
	Comercio: ["Vendedor", "Comprador", "Transportador", "Cajero"],
	Informática: [
		"Analista de sistemas",
		"Analista de datos",
		"Diseñador de bases de datos",
		"Analista de Hardware",
	],
	Ingeniería: [
		"Ingeniero civil",
		"Ingeniero mecánico",
		"Ingeniero eléctrico",
		"Ingeniero de software",
	],
	Diseño: [
		"Diseñador gráfico",
		"Diseñador web",
		"Diseñador de interfaces",
		"Diseñador de experiencia",
	],
	Deportes: [
		"Futbolista",
		"Arbitro de futbol",
		"Arbitro de baloncesto",
		"Entrenador deportivo",
	],
	Cocina: ["Chef", "Cocinero", "Mozo", "Cajero"],
	Programación: [
		"Desarrollador front-end",
		"Desarrollador back-end",
		"Desarrollador full-stack",
		"Desarrollador mobile",
		"Desarrollador web",
		"Desarrollador de aplicaciones de Escritorio",
	],
};
